groundness = """
# Instruction
You are an expert evaluator. Your task is to evaluate the quality of the responses generated by two AI models. We will provide you with the user input and a pair of AI-generated responses (Response A and Response B).
You should first read the user input carefully for analyzing the task, and then evaluate the quality of the responses based on the Criteria provided in the Evaluation section below.
You will first judge responses individually, following the Rating Rubric and Evaluation Steps.
Then you will give step-by-step explanations for your judgment, compare results to declare the winner based on the Rating Rubric and Evaluation Steps.

# Evaluation
## Metric Definition
You will be assessing groundedness, which measures the ability to provide or reference information included only in the user prompt.

## Criteria
Groundedness: The response contains information included only in the user prompt. The response does not reference any outside information.

## Rating Rubric
A number between -1 and 1 with

-1: Response A is much more ground than Response B, which is mostly ungrounded
 0: Both response A and B are equally grounded, or ungrounded.
+1: Response B is much more ground than Response A, which is mostly ungrounded

## Evaluation Steps
STEP 1: Analyze Response A based on the groundedness criteria: Identify any information in the response not present in the prompt and provide assessment according to the criterion.
STEP 2: Analyze Response B based on the groundedness criteria: Identify any information in the response not present in the prompt and provide assessment according to the criterion.
STEP 3: Compare the overall performance of Response A and Response B based on your analyses and assessment.
STEP 4: Output your assessment reasoning in the 'explanation' field.
STEP 5: Output your rating as a number between -1 and 1 in a JSON format with key 'rating' according to the Rating Rubric.

# User Inputs and AI-generated Responses
## User Inputs
### Prompt
{prompt}

## AI-generated Responses

### Response A
{responseA}

### Response B
{responseB}
"""

text_quality = """
# Instruction
You are an expert evaluator. Your task is to evaluate the quality of the responses generated by two AI models. We will provide you with the user input and a pair of AI-generated responses (Response A and Response B). You should first read the user input carefully for analyzing the task, and then evaluate the quality of the responses based on the Criteria provided in the Evaluation section below.
You will first judge responses individually, following the Rating Rubric and Evaluation Steps. Then you will give step-by-step explanations for your judgment, compare the results, and declare the winner based on the Rating Rubric and Evaluation Steps.
# Evaluation
## Metric Definition
You will be assessing the Text Quality of each model's response, which measures how effectively the text conveys clear, accurate, and engaging information that directly addresses the user's prompt, considering factors like fluency, coherence, relevance, and conciseness.

## Criteria
Coherence: The response presents ideas in a logical and organized manner, with clear transitions and a consistent focus, making it easy to follow and understand.
Fluency: The text flows smoothly and naturally, adhering to grammatical rules and using appropriate vocabulary.
Instruction following: The response demonstrates a clear understanding of the task instructions, satisfying all of the instruction's requirements.
Groundedness: The response contains information included only in the context. The response does not reference any outside information.
Verbosity: The response is appropriately concise, providing sufficient detail without using complex language to thoroughly address the prompt without being overly wordy or excessively brief.

## Rating Rubric
A number between -1 and 1 with

-1: Response A  demonstrates significantly better Text Quality than Response B as per criteria, excelling in aspects such as coherence, fluency, instruction following, groundedness, and verbosity.
 0: Response A and Response B demonstrate comparable Text Quality as per criteria, with no significant differences in aspects such as coherence, fluency, instruction following, groundedness, and verbosity.
+1: Response B demonstrates significantly better Text Quality than Response A as per criteria, excelling in aspects such as coherence, fluency, instruction following, groundedness, and verbosity.


## Evaluation Steps
STEP 1: Analyze Response A based on all the Criteria provided, including Coherence, Fluency, Instruction following, Groundedness, and Verbosity. Provide assessment according to each criterion.
STEP 2: Analyze Response B based on all the Criteria provided, including Coherence, Fluency, Instruction following, Groundedness, and Verbosity. Provide assessment according to each criterion 
STEP 3: Compare the overall performance of Response A and Response B based on your analyses and assessment of each criterion 
STEP 4: Output your assessment reasoning in the explanation field, justifying your choice by highlighting the specific strengths and weaknesses of each response in terms of Text Quality
STEP 5: Output your rating as a number between -1 and 1 in a JSON format with key 'rating' according to the Rating Rubric.

# User Inputs and AI-generated Responses
## User Inputs
### Prompt
{prompt} 

# AI-generated Response

### Response A
{responseA}

### Response B
{responseB} 
"""

summarization = """
# Instruction
You are an expert evaluator. Your task is to evaluate the quality of the responses generated by two AI models. We will provide you with the user input and a pair of AI-generated responses (Response A and Response B).
You should first read the user input carefully for analyzing the task, and then evaluate the quality of the responses based on the Criteria provided in the Evaluation section below.
You will first judge responses individually, following the Rating Rubric and Evaluation Steps.
Then you will give step-by-step explanations for your judgment, compare results to declare the winner based on the Rating Rubric and Evaluation Steps.

# Evaluation
## Metric Definition
You will be assessing summarization quality, which measures the overall ability to summarize text. Pay special attention to length constraints, such as in X words or in Y sentences. The instruction for performing a summarization task and the context to be summarized are provided in the user prompt. The response should be shorter than the text in the context. The response should not contain information that is not present in the context.

## Criteria
Instruction following: The response demonstrates a clear understanding of the summarization task instructions, satisfying all of the instruction's requirements.
Groundedness: The response contains information included only in the context. The response does not reference any outside information.
Conciseness: The response summarizes the relevant details in the original text without a significant loss in key information without being too verbose or terse.
Fluency: The response is well-organized and easy to read.

## Rating Rubric
A number between -1 and 1 with

-1: Response A summarizes the given context as per the criteria better than response B.
 0: Response A and B summarizes the given context equally well as per the criteria.
+1: Response B summarizes the given context as per the criteria better than response A.

## Evaluation Steps
STEP 1: Analyze Response A based on the summarization quality criteria: Determine how well Response A fulfills the user requirements, is grounded in the context, is concise and fluent, and provides assessment according to the criterion.
STEP 2: Analyze Response B based on the summarization quality criteria: Determine how well Response B fulfills the user requirements, is grounded in the context, is concise and fluent, and provides assessment according to the criterion.
STEP 3: Compare the overall performance of Response A and Response B based on your analyses and assessment.
STEP 4: Output your assessment reasoning in the explanation field.
STEP 5: Output your rating as a number between -1 and 1 in a JSON format with key 'rating' according to the Rating Rubric.

# User Inputs and AI-generated Responses
## User Inputs

### Prompt
{prompt}

## AI-generated Responses
### Response A
{responseA}

### Response B
{responseB}
"""

verbosity = """
# Instruction
You are an expert evaluator. Your task is to evaluate the quality of the responses generated by two AI models. We will provide you with the user input and a pair of AI-generated responses (Response A and Response B).
You should first read the user input carefully for analyzing the task, and then evaluate the quality of the responses based on the Criteria provided in the Evaluation section below.
You will first judge responses individually, following the Rating Rubric and Evaluation Steps.
Then you will give step-by-step explanations for your judgment, compare results to declare the winner based on the Rating Rubric and Evaluation Steps.

# Evaluation
## Metric Definition
You will be assessing the verbosity of each model's response, which measures its conciseness and ability to provide sufficient detail without being overly wordy or excessively brief. 

## Criteria
Verbosity: The response is appropriately concise, providing sufficient detail without using complex language to thoroughly address the prompt without being overly wordy  or excessively brief. 

## Rating Rubric
A number between -1 and 1 with

-1: Response A is more appropriately concise than Response B. It strikes a better balance between providing sufficient detail and avoiding unnecessary wordiness or excessive brevity.
 0: Response A and B are equally concise. They both strike the same level of balance between providing sufficient detail and avoiding unnecessary wordiness or excessive brevity.
+1: Response B is more appropriately concise than Response A. It strikes a better balance between providing sufficient detail and avoiding unnecessary wordiness or excessive brevity.

## Evaluation Steps
STEP 1: Analyze Response A based on the Verbosity criterion regarding completeness, conciseness, and overall balance.
STEP 2: Analyze Response B based on the Verbosity criterion regarding completeness, conciseness, and overall balance.
STEP 3: Compare the overall performance of Response A and Response B based on your analyses and assessment.
STEP 4: Output your assessment reasoning in the explanation field, justifying your choice by highlighting the specific strengths and weaknesses of each response in terms of verbosity.
STEP 5: Output your rating as a number between -1 and 1 in a JSON format with key 'rating' according to the Rating Rubric.

# User Inputs and AI-generated Responses
## User Inputs
### Prompt
{prompt} 

# AI-generated Responses

### Response A
{responseA}

### Response B
{responseB}

"""


